services:
  - type: web
    name: efootball-freaks
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      SESSION_SECRET: efootball-freaks-arnold-2025
      NODE_ENV: production